name: Biweekly Invoice Refresh

on:
  schedule:
    - cron: '0 8 */14 * *'  # Every 14 days at 8am UTC
  workflow_dispatch:

permissions:
  contents: write  # 👈 Needed to commit back to the repo

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch script
        run: python fetch_overdue_invoices.py

      - name: Commit updated CSVs for GoFleet and Zenduit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add gofleet_*_overdue_invoices_*.csv zenduit_*_overdue_invoices_*.csv || true
          git commit -m "Auto-update overdue invoices for GoFleet and Zenduit" || echo "No changes to commit"
          git pull --rebase || echo "Rebase failed, likely due to no upstream changes"
          git push || echo "Push failed, likely due to fast-forward conflict"



