name: Biweekly Invoice Refresh

on:
  schedule:
    - cron: '0 8 */14 * *'  # Every 14 days at 8 AM UTC
  workflow_dispatch:        # Allows manual triggering from GitHub UI

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch script
        run: python fetch_overdue_invoices.py

      - name: Commit updated CSV
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add zoho_overdue_invoices.csv
          git commit -m "Auto-update overdue invoices CSV" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
