name: Biweekly Invoice Refresh

on:
  schedule:
    - cron: '0 8 */14 * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt || pip install pandas requests

      - name: Run fetch script
        run: python fetch_overdue_invoices.py

      - name: Commit updated CSV
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add zoho_overdue_invoices.csv
          git commit -m "🔄 Auto-update overdue invoice data"
          git push